site_name: Tech Radar

pages:
    - Welcome:
      - Overview: index.md
      - Resourcing: resourcing.md
    - Getting Started:
      - The People: people.md
      - Skills: skills.md
      - Tech Radar: radar.md

theme:
  name: 'material'
  logo:
    icon: 'cast_connected'
  favicon: 'images/favicon.png'
  palette:
    primary: 'orange'
    accent: 'orange'

  feature:
    tabs: true
    
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.details

